<?php

namespace Helper;
use Swood\Debug as D;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-21 at 18:06:02.
 */
class ArrTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Arr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Arr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Helper\Arr::traversalByDepth
     * @todo   Implement testTraversalByDepth().
     */
    public function testTraversalByDepth() {
        $arr = [
            [11,22,33],
            [44,55,66],
            [77,88,99],
            [12,23,45,67],
            [87,65,43,21],
        ];

        $arr2 = $arr;
        $it = Arr::traversalByDepth($arr2, 2);
        foreach ($it as $cursor => $v) {
            $cursor[0][$cursor[1]] = $v / 10;
        }

        D::dt($arr);
        D::dt($arr2);
    }

    /**
     * @covers Helper\Arr::traversal
     * @todo   Implement testTraversal().
     */
    public function testTraversal() {
        $arr = [
            [11,[77,88,99],33],
            [[44,55,[87,65,43,21]],23,45,67],
        ];

        $arr2 = $arr;
        $it = Arr::traversal($arr2);
        foreach ($it as $cursor => $v) {
            $cursor[0][$cursor[1]] = $v / 10;
        }

        D::dt($arr);
        D::dt($arr2);
    }

}
