<?php

namespace Swood\Launcher\App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-29 at 18:37:10.
 */
class WorkerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Worker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $app = new App([]);
        $this->object = new Worker($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Swood\Launcher\App\Worker::call
     * @todo   Implement testCall().
     */
    public function testCall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Swood\Launcher\App\Worker::taskFinish
     * @todo   Implement testTaskFinish().
     */
    public function testTaskFinish() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Swood\Launcher\App\Worker::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Swood\Launcher\App\Worker::stop
     * @todo   Implement testStop().
     */
    public function testStop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Swood\Launcher\App\Worker::error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
